"use strict";

/* ========================================
   CampuSphere — Guided VR route catalog (BE.4)

   Frozen, source-controlled catalog of guided VR walkthroughs that are
   defined by STABLE NATURAL IDENTITIES only:

     - destination_name       canonical building display name (matched via
                              services/routeAvailability.canonicalKey by the
                              caller — this module performs no normalization
                              of its own so there is exactly ONE canonical-name
                              function in the codebase);
     - destination_node_key   the route-graph node the walkthrough must end at;
     - arrival_scene_key      the ONLY scene whose presence as the final
                              verified step counts as truthful arrival;
     - scene_keys             the owner-approved ordered panorama sequence.

   HARD RULES:
   - Natural keys only. This module must NEVER contain backend numeric ids
     (vr_scenes.id, buildings.id, route_nodes.id are backend-local and must
     never be compared or copied across MySQL/Supabase).
   - No imports, no env reads, no side effects — pure frozen data, safe to
     require from any layer.
   - The catalog describes the GUIDED walkthrough only. Post-arrival interior
     scenes (e.g. scene-cas-1st-floor-2 / -3) are deliberately NOT steps; they
     stay reachable through the arrival scene's own hotspots in Free Roam.
   - Adding a destination here does not by itself make it arrivable: the
     runtime still verifies every scene key and every forward/reverse
     directional link in the ACTIVE VR data source and truthfully reports
     partial coverage when the chain is incomplete.
   - A destination listed in DEFERRED_GUIDED_VR_DESTINATIONS remains routable
     on the campus map, but guided VR must fail closed with an explicit
     unavailable state until the owner supplies and approves its panorama
     sequence. A destination must never appear in both collections.
   ======================================== */

const GUIDED_VR_ROUTES = Object.freeze([
  Object.freeze({
    destination_name: "Academic Building III",
    destination_node_key: "acad-3",
    arrival_scene_key: "scene-cas-1st-floor",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-general-road-31",
      "scene-general-road-32",
      "scene-general-road-33",
      "scene-general-road-33-5",
      "scene-general-road-37",
      "scene-general-road-38",
      "scene-general-road-38-5",
      "scene-general-road-39",
      "scene-cas-1st-floor",
    ]),
  }),
  Object.freeze({
    destination_name: "Academic Building IV",
    destination_node_key: "ccs",
    arrival_scene_key: "scene-ccs-1st-floor",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-general-road-31",
      "scene-general-road-32",
      "scene-general-road-33",
      "scene-general-road-33-5",
      "scene-general-road-37",
      "scene-general-road-38",
      "scene-general-road-94",
      "scene-ccs-1st-floor",
    ]),
  }),

  Object.freeze({
    destination_name: "Academic Building VI",
    destination_node_key: "acad-6",
    arrival_scene_key: "scene-chs-1st-floor-001",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-general-road-31",
      "scene-general-road-32",
      "scene-general-road-33",
      "scene-general-road-33-5",
      "scene-general-road-37",
      "scene-general-road-38",
      "scene-general-road-94",
      "scene-general-road-93",
      "scene-general-road-92",
      "scene-general-road-91",
      "scene-chs-1st-floor-001",
    ]),
  }),

  Object.freeze({
    destination_name: "Academic Building V",
    destination_node_key: "acad-5",
    arrival_scene_key: "scene-acad-5-1st-floor-7",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-general-road-31",
      "scene-general-road-32",
      "scene-general-road-33",
      "scene-general-road-33-5",
      "scene-general-road-37",
      "scene-general-road-38",
      "scene-general-road-38-5",
      "scene-general-road-39",
      "scene-general-road-41",
      "scene-general-road-39",
      "scene-general-road-41",
      "scene-general-road-42",
      "scene-general-road-43",
      "scene-general-road-44",
      "scene-general-road-45",
      "scene-general-road-46",
      "scene-general-road-47",
      "scene-general-road-48",
      "scene-general-road-49",
      "scene-acad-5-1st-floor-7",
    ]),
  }),

  Object.freeze({
    destination_name: "Green Building",
    destination_node_key: "green",
    arrival_scene_key: "scene-green-1st-floor-7",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-general-road-31",
      "scene-general-road-32",
      "scene-general-road-33",
      "scene-general-road-34",
      "scene-general-road-35",
      "scene-green-1st-floor-7",
    ]),
  }),

  Object.freeze({
    destination_name: "Supply & Property Building",
    destination_node_key: "supply-property-bldg",
    arrival_scene_key: "scene-supply-1st-floor-001",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-general-road-31",
      "scene-general-road-32",
      "scene-supply-1st-floor-001",
    ]),
  }),

  Object.freeze({
    destination_name: "Academic Building II",
    destination_node_key: "acad-2",
    arrival_scene_key: "scene-acad-2-1st-floor-17",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-general-road-31",
      "scene-general-road-32",
      "scene-general-road-33",
      "scene-general-road-34",
      "scene-general-road-35",
      "scene-general-road-36",
      "scene-general-road-59",
      "scene-general-road-60",
      "scene-acad-2-1st-floor-17",
    ]),
  }),

  Object.freeze({
    destination_name: "CITD Building",
    destination_node_key: "citd",
    arrival_scene_key: "scene-citd-1st-floor-5",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-citd-1st-floor-5",
    ]),
  }),

  Object.freeze({
    destination_name: "MULTI-PURPOSE-BUILDING I",
    destination_node_key: "multi-1",
    arrival_scene_key: "scene-audit-building-006",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-27",
      "scene-general-road-28",
      "scene-general-road-29",
      "scene-general-road-30",
      "scene-general-road-31",
      "scene-general-road-32",
      "scene-general-road-33",
      "scene-general-road-34",
      "scene-general-road-35",
      "scene-general-road-36",
      "scene-general-road-59",
      "scene-general-road-60",
      "scene-general-road-61",
      "scene-general-road-62",
      "scene-general-road-63",
      "scene-general-road-64",
      "scene-audit-building-006",
    ]),
  }),
  Object.freeze({
    destination_name: "Gymnasium",
    destination_node_key: "gym",
    arrival_scene_key: "scene-gym-1st-floor-bleacher-1",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-24",
      "scene-general-road-25",
      "scene-gym-1st-floor-bleacher-1",
    ]),
  }),
  Object.freeze({
    destination_name: "Villafuerte Hall",
    destination_node_key: "villafuerte-hall",
    arrival_scene_key: "scene-vh-1",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-24",
      "scene-general-road-25",
      "scene-pearl-park-2",
      "scene-pearl-park-17",
      "scene-vh-1",
    ]),
  }),
  Object.freeze({
    destination_name: "Pearl Park",
    destination_node_key: "pearl-park",
    arrival_scene_key: "scene-pearl-park-2",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-general-road-22",
      "scene-general-road-23",
      "scene-general-road-24",
      "scene-general-road-25",
      "scene-pearl-park-2",
    ]),
  }),

  Object.freeze({
    destination_name: "Laboratory & Shop Building",
    destination_node_key: "lab-shop",
    arrival_scene_key: "scene-lab-and-shop-building-001",
    scene_keys: Object.freeze([
      "scene-guard-house",
      "scene-general-road-10",
      "scene-general-road-11",
      "scene-general-road-12",
      "scene-general-road-13",
      "scene-general-road-14",
      "scene-general-road-15",
      "scene-duran-1st-floor-13",
      "scene-general-road-19",
      "scene-general-road-20",
      "scene-general-road-21",
      "scene-lab-and-shop-building-001",
    ]),
  }),
]);

const DEFERRED_GUIDED_VR_DESTINATIONS = Object.freeze([]);

module.exports = {
  GUIDED_VR_ROUTES,
  DEFERRED_GUIDED_VR_DESTINATIONS,
};
