'use strict';

/*
 * Per-request diagnostics context.
 *
 * The identifier is generated by the server, is intentionally not accepted
 * from a request header, and is never copied into a response, session object,
 * or database row. AsyncLocalStorage lets a late express-session callback
 * retain the same identifier as the request that created it.
 */
const crypto = require('node:crypto');
const { AsyncLocalStorage } = require('node:async_hooks');

const REQUEST_ID_PATTERN = /^[a-f0-9]{32}$/;
const NO_REQUEST_ID = '-';
const storage = new AsyncLocalStorage();
const REQUEST_ID = Symbol('campusphere.requestCorrelationId');

function safeRequestCorrelationId(value) {
  return typeof value === 'string' && REQUEST_ID_PATTERN.test(value)
    ? value
    : NO_REQUEST_ID;
}

function requestCorrelationId(req) {
  const requestValue = req && req[REQUEST_ID];
  if (REQUEST_ID_PATTERN.test(String(requestValue || ''))) return requestValue;

  const context = storage.getStore();
  return safeRequestCorrelationId(context && context.requestId);
}

function requestDiagnostics(req, _res, next) {
  const requestId = crypto.randomBytes(16).toString('hex');
  Object.defineProperty(req, REQUEST_ID, {
    configurable: false,
    enumerable: false,
    value: requestId,
    writable: false,
  });
  return storage.run({ requestId }, next);
}

function elapsedBucket(elapsedMs) {
  if (!Number.isFinite(elapsedMs) || elapsedMs < 0) return 'unknown';
  if (elapsedMs < 250) return 'lt250ms';
  if (elapsedMs < 1000) return '250to999ms';
  if (elapsedMs < 2000) return '1000to1999ms';
  return 'gte2000ms';
}

module.exports = {
  elapsedBucket,
  requestCorrelationId,
  requestDiagnostics,
  safeRequestCorrelationId,
};
