-- =============================================================================
-- CampuSphere - Admin Content And Audit Logs
-- File: database/supabase/0006_admin_content_and_logs.sql
-- Milestone 7, Section 7.2
-- =============================================================================
--
-- Purpose
--   Bring the Supabase backend to the Milestone 7 admin baseline, mirroring
--   database/schema.sql and database/seed.js so MySQL and Supabase stay in
--   lockstep:
--     1. Add the privacy-minimal `system_logs` audit table (seeded empty).
--     2. Seed / refresh the canonical FAQ set (6 rows) idempotently.
--     3. Refresh the 10 canonical `system_settings` values, correcting stale
--        founding year / contact phone / email / website to truthful CSPC
--        values.
--
-- Apply order
--   This file is the sixth Supabase migration. Apply in order:
--     1. database/supabase/0001_initial_schema.sql
--     2. database/supabase/0002_seed_data.sql
--     3. database/supabase/0003_auth_profile_functions.sql
--     4. database/supabase/0004_building_backfill.sql
--     5. database/supabase/0005_building_write_functions.sql
--     6. database/supabase/0006_admin_content_and_logs.sql            <-- this file
--   Re-applying is safe: the table uses CREATE TABLE / INDEX IF NOT EXISTS,
--   the FAQ seed upserts by exact question, the settings seed upserts
--   ON CONFLICT (setting_key), and the grants / revokes are repeatable.
--
-- Privacy and immutability (audit)
--   system_logs stores WHAT happened plus a safe message ONLY. It NEVER stores
--   IP addresses, passwords, request bodies, tokens, cookies, session IDs,
--   OAuth subjects, secrets, or stack traces. There is no updated_at column
--   and no audit update / delete function: rows are immutable through the
--   application. service_role is granted SELECT + INSERT only, and
--   UPDATE / DELETE / TRUNCATE are revoked, so the audit trail cannot be
--   rewritten even with the service-role key.
--
-- Access decision
--   Every grant below is scoped to service_role ONLY -- never anon, never
--   authenticated. The browser, EJS, and public JS never see the service-role
--   key (see 0001 Section D and the config/supabase.js header).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. system_logs -- Postgres equivalent of the database/schema.sql table
-- -----------------------------------------------------------------------------
--   actor_user_id is bigint to match users.id (Supabase identity); the MySQL
--   table uses INT to match its INT users.id. ON DELETE SET NULL keeps audit
--   history when a user row is later removed.
CREATE TABLE IF NOT EXISTS system_logs (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      varchar(50)   NOT NULL,
    action          varchar(100)  NOT NULL,
    outcome         varchar(20)   NOT NULL,
    actor_user_id   bigint
        REFERENCES users(id) ON DELETE SET NULL,
    attempted_email varchar(100),
    actor_role      varchar(30),
    target_type     varchar(50),
    target_id       varchar(100),
    message         varchar(500)  NOT NULL,
    created_at      timestamptz   NOT NULL DEFAULT now()
);

-- Newest-first listing.
CREATE INDEX IF NOT EXISTS system_logs_created_at_idx
    ON system_logs (created_at DESC);

-- Bounded event_type + outcome filtering, newest-first within a filter.
CREATE INDEX IF NOT EXISTS system_logs_event_outcome_created_idx
    ON system_logs (event_type, outcome, created_at DESC);


-- -----------------------------------------------------------------------------
-- 2. Canonical FAQ seed (6 rows) -- idempotent upsert by exact question
-- -----------------------------------------------------------------------------
-- faqs has no UNIQUE on question (see 0001 section B.2), so ON CONFLICT cannot
-- be used. Refresh existing canonical rows first, then insert any that are
-- missing. Admin-created / unrelated FAQs are never touched, and re-running
-- never duplicates a canonical row.
UPDATE faqs AS f
   SET answer        = c.answer,
       category      = c.category,
       display_order = c.display_order
  FROM (VALUES
      ('How do I open the campus map?',
       'Sign in to CampuSphere, then choose Campus Map from the navigation. The interactive map opens for signed-in students, instructors, guests, and admins.',
       'Campus Map', 1),
      ('How do I find a building, office, or service?',
       'Use Campus Map search to find buildings, offices, services, categories, landmarks, or routes. On the Buildings page, search by building name or description and use the category filters. Select a result to open its details.',
       'Campus Map', 2),
      ('How do I get walking directions to a building?',
       'Open a building on the Campus Map and set it as your destination. If a predefined route is available, CampuSphere shows its ordered walking directions from the Main Gate; otherwise it clearly reports that no predefined route is available yet.',
       'Navigation', 3),
      ('How do I start a guided VR route?',
       'Buildings linked to an available guided VR route show a Start VR Route button on the Campus Map and Buildings pages. Select it to open the guided VR tour, then use the on-screen points to move between scenes. Scenes without an uploaded panorama display a readable fallback instead of a broken viewer.',
       'VR Tour', 4),
      ('Can I use CampuSphere offline?',
       'After you open a page once while online, you can reopen the campus map, the building directory, and VR routes you already viewed without a connection. Signing in and live updates still need internet.',
       'Offline Access', 5),
      ('How do I update my profile information?',
       'Open Update Profile from your dashboard to edit your name and role-specific details. For security, your email address and account role cannot be changed from this form.',
       'Account', 6)
  ) AS c(question, answer, category, display_order)
 WHERE f.question = c.question;

INSERT INTO faqs (question, answer, category, display_order)
SELECT c.question, c.answer, c.category, c.display_order
  FROM (VALUES
      ('How do I open the campus map?',
       'Sign in to CampuSphere, then choose Campus Map from the navigation. The interactive map opens for signed-in students, instructors, guests, and admins.',
       'Campus Map', 1),
      ('How do I find a building, office, or service?',
       'Use Campus Map search to find buildings, offices, services, categories, landmarks, or routes. On the Buildings page, search by building name or description and use the category filters. Select a result to open its details.',
       'Campus Map', 2),
      ('How do I get walking directions to a building?',
       'Open a building on the Campus Map and set it as your destination. If a predefined route is available, CampuSphere shows its ordered walking directions from the Main Gate; otherwise it clearly reports that no predefined route is available yet.',
       'Navigation', 3),
      ('How do I start a guided VR route?',
       'Buildings linked to an available guided VR route show a Start VR Route button on the Campus Map and Buildings pages. Select it to open the guided VR tour, then use the on-screen points to move between scenes. Scenes without an uploaded panorama display a readable fallback instead of a broken viewer.',
       'VR Tour', 4),
      ('Can I use CampuSphere offline?',
       'After you open a page once while online, you can reopen the campus map, the building directory, and VR routes you already viewed without a connection. Signing in and live updates still need internet.',
       'Offline Access', 5),
      ('How do I update my profile information?',
       'Open Update Profile from your dashboard to edit your name and role-specific details. For security, your email address and account role cannot be changed from this form.',
       'Account', 6)
  ) AS c(question, answer, category, display_order)
 WHERE NOT EXISTS (SELECT 1 FROM faqs f WHERE f.question = c.question);


-- -----------------------------------------------------------------------------
-- 3. Canonical system_settings refresh (10 keys)
-- -----------------------------------------------------------------------------
-- setting_key is the PRIMARY KEY, so ON CONFLICT DO UPDATE refreshes values
-- (school_founded, contact_phone, contact_email, contact_website are corrected
-- to truthful CSPC values) while leaving any admin-added keys untouched. These
-- match database/seed.js after its models/data.js source values were
-- corrected, so both backends agree by natural key.
INSERT INTO system_settings (setting_key, setting_value) VALUES
    ('school_name',        'Camarines Sur Polytechnic Colleges'),
    ('school_acronym',     'CSPC'),
    ('school_address',     'Nabua, Camarines Sur, Philippines'),
    ('school_founded',     '1983'),
    ('school_description', 'Camarines Sur Polytechnic Colleges is a state-funded institution of higher learning in Nabua, Camarines Sur providing quality education in engineering, technology, and other disciplines.'),
    ('contact_address',    'San Miguel, Nabua, Camarines Sur 4434'),
    ('contact_phone',      '(054) 288 4421 to 23'),
    ('contact_email',      'mail@cspc.edu.ph'),
    ('contact_website',    'https://cspc.edu.ph'),
    ('contact_hours',      'Monday - Friday, 8:00 AM - 5:00 PM')
ON CONFLICT (setting_key) DO UPDATE
    SET setting_value = EXCLUDED.setting_value;


-- -----------------------------------------------------------------------------
-- 4. Service-role grants for system_logs (service_role ONLY)
-- -----------------------------------------------------------------------------
-- 0001 Section D set ALTER DEFAULT PRIVILEGES that may auto-grant full DML on
-- new tables to service_role. For the audit trail we keep INSERT + SELECT and
-- explicitly REVOKE UPDATE / DELETE / TRUNCATE so audit rows stay immutable
-- even with the service-role key. anon and authenticated receive nothing.
GRANT SELECT, INSERT ON TABLE public.system_logs TO service_role;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE public.system_logs FROM service_role;
GRANT USAGE, SELECT ON SEQUENCE public.system_logs_id_seq TO service_role;

REVOKE ALL ON TABLE public.system_logs FROM anon, authenticated;

-- =============================================================================
-- End of 0006_admin_content_and_logs.sql
-- =============================================================================
