-- =============================================================================
-- 0012_room_schedules.sql
-- Milestone 11, Section 11.3 — Room scheduling schema (Supabase/MySQL parity).
-- =============================================================================
-- Creates the server-only `public.room_schedules` table for real admin-managed
-- room/facility schedule entries tied to a building, per the approved domain
-- contract (docs/room-scheduling-domain-contract.md). This mirrors the MySQL
-- `room_schedules` table added to database/schema.sql in the same section:
-- same columns, same allowlists (enforced here as CHECK constraints instead of
-- MySQL ENUMs), same two read-path indexes, same referential behavior
-- (building_id RESTRICT — no silent cascade of schedules on building delete;
-- created_by_user_id SET NULL, mirroring news_announcements.author_id).
--
-- APPLY: run this file in the Supabase SQL editor. Supabase SQL under
-- database/supabase/ is applied MANUALLY by the project owner; this file being
-- present is the static declaration only. It is NOT applied automatically and
-- must be owner-applied before any live Supabase schedule-runtime verification
-- (Sections 11.4–11.8). Every statement is idempotent (IF NOT EXISTS / safe
-- REVOKE+GRANT), so the file is SAFE TO RE-RUN.
--
-- Domain notes
--   - location_label / floor_label are free text: rooms and facilities exist
--     only inside buildings.details JSON, not as rows, so there is nothing to
--     foreign-key. No requirement that labels match a details entry.
--   - Dates/times are naive campus-local wall time (Asia/Manila); an entry
--     lives entirely within one calendar day (end_time > start_time is
--     enforced by application validation, not a DB constraint, matching the
--     MySQL side).
--   - No conflict/overlap enforcement in v1: overlapping rows are allowed.
--   - This is campus operations data only — no SIS, enrollment, assigned
--     classes, instructor teaching loads, attendance, grading, or academic
--     records.
--
-- Privacy / security
--   - Browser roles `anon` and `authenticated` receive NO privileges and NO
--     RLS policies, so the Data API (PostgREST) cannot read or write schedule
--     rows directly. All access goes through the server-only client
--     (config/supabase.js, service_role) and the repositories/ layer.
--   - CampuSphere does NOT use Supabase Auth; it keeps Express sessions,
--     bcrypt local login, and Google OAuth.
--   - As documented in 0001 Section D, the project disables "Automatically
--     expose new tables", so service_role does not auto-inherit privileges on
--     a newly created table; the explicit GRANTs below (table + identity
--     sequence) are required for server-side reads/writes to work and keep a
--     fresh Supabase setup repeatable from this file alone.
--   - created_by_user_id is server-only metadata and must never be exposed on
--     public/user-facing surfaces.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.room_schedules (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              varchar(150) NOT NULL,
    schedule_date      date         NOT NULL,
    start_time         time         NOT NULL,
    end_time           time         NOT NULL,
    audience           text         NOT NULL DEFAULT 'all'
        CONSTRAINT room_schedules_audience_check
        CHECK (audience IN ('all', 'student-cspc', 'instructor', 'guest', 'admin')),
    status             text         NOT NULL DEFAULT 'scheduled'
        CONSTRAINT room_schedules_status_check
        CHECK (status IN ('scheduled', 'cancelled', 'completed')),
    building_id        bigint       NOT NULL
        REFERENCES public.buildings(id) ON DELETE RESTRICT,
    location_type      text         NOT NULL
        CONSTRAINT room_schedules_location_type_check
        CHECK (location_type IN ('room', 'facility')),
    location_label     varchar(120) NOT NULL,
    floor_label        varchar(80),
    description        varchar(1000),
    created_by_user_id bigint
        REFERENCES public.users(id) ON DELETE SET NULL,
    created_at         timestamptz  NOT NULL DEFAULT now(),
    updated_at         timestamptz  NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- Indexes (read paths from the domain contract; MySQL parity:
-- idx_room_schedules_building_date / idx_room_schedules_schedule_date)
-- -----------------------------------------------------------------------------
-- Building detail view: WHERE building_id = ? AND schedule_date range,
-- ordered by schedule_date (composite covers WHERE + ORDER BY).
CREATE INDEX IF NOT EXISTS room_schedules_building_date_idx
    ON public.room_schedules (building_id, schedule_date);

-- Bounded date-range listings across buildings.
CREATE INDEX IF NOT EXISTS room_schedules_schedule_date_idx
    ON public.room_schedules (schedule_date);

-- -----------------------------------------------------------------------------
-- Row Level Security (no browser policies)
-- -----------------------------------------------------------------------------
-- Enable RLS with NO policies so anon/authenticated (which respect RLS) can
-- never read or write schedule rows through the Data API. service_role
-- bypasses RLS and is granted explicit privileges below.
ALTER TABLE public.room_schedules ENABLE ROW LEVEL SECURITY;

-- -----------------------------------------------------------------------------
-- Privileges (service_role only)
-- -----------------------------------------------------------------------------
-- Strip any implicit/default privileges from PUBLIC and from the browser roles,
-- then grant table DML to service_role only. No grants are created for anon or
-- authenticated.
REVOKE ALL ON TABLE public.room_schedules FROM PUBLIC;
REVOKE ALL ON TABLE public.room_schedules FROM anon;
REVOKE ALL ON TABLE public.room_schedules FROM authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.room_schedules TO service_role;

-- The identity column's backing sequence also needs explicit access for
-- service_role inserts (same "no auto-expose" reason as the table grant).
GRANT USAGE, SELECT ON SEQUENCE public.room_schedules_id_seq TO service_role;

-- =============================================================================
-- End 0012_room_schedules.sql
-- =============================================================================
