-- =============================================================================
-- 0020_room_schedule_documents.sql
-- Semester-long room schedule images and direct VR-hotspot references.
-- =============================================================================
-- Owner-applied only. This additive declaration does not upload media, seed
-- schedule records, modify legacy room_schedules rows, or relink hotspots.

CREATE TABLE IF NOT EXISTS public.room_schedule_documents (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_id            bigint       NOT NULL
        CONSTRAINT room_schedule_documents_building_fk
        REFERENCES public.buildings(id) ON DELETE RESTRICT,
    location_type          text         NOT NULL
        CONSTRAINT room_schedule_documents_location_type_check
        CHECK (location_type IN ('room', 'facility')),
    location_label         varchar(120) NOT NULL,
    floor_label            varchar(80),
    location_key           char(64)     NOT NULL
        CONSTRAINT room_schedule_documents_location_key_check
        CHECK (location_key ~ '^[0-9a-f]{64}$'),
    semester               text         NOT NULL
        CONSTRAINT room_schedule_documents_semester_check
        CHECK (semester IN ('first-semester', 'second-semester', 'midyear')),
    school_year            char(9)      NOT NULL
        CONSTRAINT room_schedule_documents_school_year_check
        CHECK (
            school_year ~ '^[0-9]{4}-[0-9]{4}$'
            AND substring(school_year from 1 for 4)::integer BETWEEN 2000 AND 2199
            AND substring(school_year from 6 for 4)::integer =
                substring(school_year from 1 for 4)::integer + 1
        ),
    image_url              varchar(1000) NOT NULL,
    cloudinary_public_id   varchar(255),
    created_by_user_id     bigint
        CONSTRAINT room_schedule_documents_creator_fk
        REFERENCES public.users(id) ON DELETE SET NULL,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT room_schedule_documents_location_unique UNIQUE (building_id, location_key)
);

CREATE INDEX IF NOT EXISTS room_schedule_documents_building_term_idx
    ON public.room_schedule_documents (building_id, semester, school_year);

ALTER TABLE public.room_schedule_documents ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.room_schedule_documents FROM PUBLIC;
REVOKE ALL ON TABLE public.room_schedule_documents FROM anon;
REVOKE ALL ON TABLE public.room_schedule_documents FROM authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.room_schedule_documents TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.room_schedule_documents_id_seq TO service_role;

ALTER TABLE public.vr_hotspots
    ADD COLUMN IF NOT EXISTS schedule_document_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'vr_hotspots_schedule_document_fk'
           AND conrelid = 'public.vr_hotspots'::regclass
    ) THEN
        ALTER TABLE public.vr_hotspots
            ADD CONSTRAINT vr_hotspots_schedule_document_fk
            FOREIGN KEY (schedule_document_id)
            REFERENCES public.room_schedule_documents(id)
            ON DELETE RESTRICT;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS vr_hotspots_schedule_document_idx
    ON public.vr_hotspots (schedule_document_id);

-- Legacy schedule_building_id/location fields intentionally remain available
-- for the read-only transition fallback. They are not populated by the new UI.
-- =============================================================================
